<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-SpeakUp.UserService-d2c265d8-8aa2-4def-8bba-2c0314221f63</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Dapper" Version="2.1.66" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.10"/>
        <PackageReference Include="SpeakUp.Common" Version="1.3.0" />
        <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
    </ItemGroup>
</Project>
